name: Reusable workflow. Using test API module

on:
  workflow_call:
    inputs:
      MODULE_NAME:
        description: "Using for choice specified module when test application."
        required: true
        type: string
      JAVA_VERSION:
        description: "Using for set version Java in build"
        default: "17"
        required: false
        type: string
    secrets:
      SECRET_GITHUB_TOKEN:
        required: true
      SECRET_GITHUB_USERNAME:
        required: true

jobs:
  api-test-module-workflow:
    runs-on: custom
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ inputs.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.JAVA_VERSION }}
          distribution: 'zulu'
#          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test application with Gradle
        run: ./gradlew test -p ${{ inputs.MODULE_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ secrets.SECRET_GITHUB_USERNAME }}
