name: Reusable workflow. Using test API module

on:
  workflow_call:
    inputs:
      MODULE_NAME:
        description: "Using for choice specified module when test application."
        required: true
        type: string

jobs:
  api-test-module-workflow:
    runs-on: custom
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test application with Gradle
        run: ./gradlew test -p ${{ inputs.MODULE_NAME }}