name: Reusable workflow. Using to build and publish lib to GitHub Packages

on:
  workflow_call:
    inputs:
      MODULE_NAME:
        description: "Using for choice specified module when build application. 
          If not present - used project directory for build and test"
        default: .
        type: string
      IS_TEST_ENABLED:
        description: "Using for start test before pushing if value is true."
        default: false
        type: boolean
      JAVA_VERSION:
        description: "Using for set version Java in build"
        default: "17"
        required: false
        type: string

jobs:
  api-lib-publish:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ inputs.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.JAVA_VERSION }}
          distribution: 'zulu'
          cache: 'gradle'
          settings-path: ${{ github.workspace }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        if: ${{ inputs.IS_TEST_ENABLED }}
        run: ./gradlew test -p ${{ inputs.MODULE_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ secrets.SECRET_GITHUB_USERNAME }}

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Publish package
        run: ./gradlew publish -p ${{ inputs.MODULE_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_RW_PACKAGES_AND_REPOS }}
          GITHUB_USERNAME: ${{ secrets.GH_USER_CAN_READ_PACKAGES }}
